services:
  fastapi:
    build: .
    ports:
      - "8321:8321"
    environment:
      - DATABASE_URL=postgresql://krishna:1122@rss_newsapp_db:5432/youtube_cm
      - PIXABAY_API_KEY=49326456-41725d5dc7f4b0f0e4f587cc9
      - RSSBRIDGE_HOST=https://rssbridge.krishna.quest
      - METUBE_URL=https://metube.krishna.quest
      - NITTER_URL=https://nitter.space
      - PROJECTS_ROOT=/app/data/youtube-videos
      - DAILY_REPORT_DIR=/app/data/daily_report
    volumes:
      - /mnt/youtube-cm/youtube-data:/app/data
      - .:/app
    restart: unless-stopped
    networks:
      - db-net
    depends_on:
      - rss_newsapp_db

  rss_newsapp_db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=krishna
      - POSTGRES_PASSWORD=1122
      - POSTGRES_DB=youtube_cm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-net
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  db-net:
    external: true  # Make sure this is already created: docker network create db-net
